### ISSUE TITLE
Waiting for images to load before applying auto initialize

### ISSUE THREAD

**Issue by JCallico** [mattbanks/jQuery.equalHeights#12]
Hi Matt

I experienced the following  issue with the plugin auto initialize feature:
- When the page was first loaded it will work as expected.
- When the page was refreshed using Ctrl-F5, resize won't work properly. I found out later it was because some images were been reloaded.

Base on this recommendation (http://stackoverflow.com/questions/544993/official-way-to-ask-jquery-wait-for-all-images-to-load-before-executing-somethin) I wrapped the auto initialization code into a window.load function, like this:

    $(window).load(function() {
        // auto-initialize plugin
        $('[data-equal]').each(function() {
            var $this = $(this),
                target = $this.data('equal');
            $this.find(target).equalHeights();
        });
    });

... and now everything works now as expected.

**Comment by vandres** [comment]
I can confirm the issue. Please fix

**Comment by mattbanks** [comment]
Can one of  you submit a pull request against the develop branch? I'll merge it and tag a new release! Sorry I haven't had time to get to this - tons of client work has been in the way.

**Comment by mattbanks** [comment]
Options for this got merged into master today and tagged in a new release
