### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by osartun** [mattbanks/jQuery.equalHeights#17]
Could you publish jQuery.equalHeights on npm?
https://docs.npmjs.com/misc/developers

Unfortunately there's already another package with the same name, so you have to choose a slightly different one. :confused: 
https://www.npmjs.com/package/jquery-equalheights

**Comment by mattbanks** [comment]
Done and done :smile: 

https://www.npmjs.com/package/jquery.equalheights

**Comment by osartun** [comment]
Awesome! Thanks! :smiley:
