### ISSUE TITLE
Version 1.5.3 doesn't work

### ISSUE THREAD

**Issue by fheider** [mattbanks/jQuery.equalHeights#18]
After update to new version no heights are set.
In Firebug there is no manipulation to the elements.
Downgrade via bower to version 1.5.2 solved it and it worked.

Browser: FF42

**Comment by mattbanks** [comment]
Any chance you put an example in Codepen or something? If if doesn't work, I can roll back to 1.5.2, but I just want to make sure. It works in the example page, so I just want to verify with something else.

**Comment by fheider** [comment]
http://codepen.io/anon/pen/bEdebv

FF42 failed
Chrome48DEV success
Opera31 success
Safari5 success
Edge20 success

**Comment by mattbanks** [comment]
Interesting that it works everywhere except Firefox. I'm in the middle of a project submission and am giving a talk Thursday evening, so I'll try to look at this on Friday or over the weekend for a possible fix.

**Comment by janjaap** [comment]
Having the same problem here in Firefox. Where before `$('.elements-selector').equalHeights()` would render the desired result on 1.5.2, the same call doesn't do anything in 1.5.3. 
Only in Firefox. Using the latest; 42.

**Comment by mattbanks** [comment]
I just rolled back to v1.5.2 in master. Everything from v1.5.3 is now in the develop branch and I'll work on it as soon as I have time. If anyone has a chance to take a look, please do and submit a pull request against develop :)

Tagging @osartun for possibly taking a look.

**Comment by osartun** [comment]
Oh! :flushed: I'll try looking into this asap, but probably won't have time before next week.

**Comment by stefangrund** [comment]
Same problem here: Firefox v49.

**Comment by osartun** [comment]
Oh dear, I remember this.
Unfortunately we don't use equalHeights anymore in our projects as we switched to flexbox-based approaches or to fixed heights.
That's why it passed completely out of my mind. I'm not sure how soon I'd be able to look into this. Maybe you have to revert my changes altogether.
