### ISSUE TITLE
Recalculate sizes after window resized

### ISSUE THREAD

**Issue by Briareos17** [mattbanks/jQuery.equalHeights#19]
I have an issue with bootstrap, when window size changes, my blocks gets new @media but heights the same, so texts glitching.
![screenshot at 16-15-45](https://cloud.githubusercontent.com/assets/2332158/14143200/b052ed08-f692-11e5-9104-fa8f258506b1.png)

**Comment by mattbanks** [comment]
For now, you'll have to to wrap a call to `equalHeights()` in the `$(window).resize()` event, like this - https://github.com/mattbanks/jQuery.equalHeights/issues/7#issuecomment-27141871

There is a more robust responsive solution in the `develop` branch, but it needs some work. I'm pretty busy with projects right now, but if anyone wants to take a look, please do and submit a PR and I can push the new version.
